project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Quarto---To Tell Your Story with Data"
  description: "Government Advances in Statistical Programming (GASP) 2025"

  repo-url: https://github.com/ivelasq/2025-06-26_intro_to_quarto
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#2b3d5b"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: 00-introduction/index.qmd
        text: 00 - Introduction
      - href: 01-documents/index.qmd
        text: 01 - Documents
      - href: 02-projects/index.qmd
        text: 02 - Projects
      - href: 03-theming/index.qmd
        text: 03 - Theming
      - href: 04-publishing/index.qmd
        text: 04 - Publishing
        
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Isabella Velásquez"
    background: "#D1D9E3"

format:
  html:
    theme:
      light: [brand, style.scss]
    linkcolor: "#991b1f"
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Open Sans"

execute:
  freeze: auto
  echo: true